name: Run Tests
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: /
          npm run build
          npm test
    env:
      CI: true
