name: Run Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: |
            packages/alpinejs
            packages/csp
            packages/history
            packages/intersect
            packages/persist
            packages/morph
            packages/trap
      - run: npm run build
